name: Test build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Git checkout master
      uses: actions/checkout@v2
    
    - name: Yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Build production
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build:prod
