name: Deploy to github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
   
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: start:prod
    - name: Log filesystem
      run: ls -a
