name: Deploy to github pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Git checkout master
      uses: actions/checkout@v2
    
    - name: Yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Build production
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build:prod

    - name: Git checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: gh-pages
 
    - name: Remove all but build from filesystem
      run: |
        find . -mindepth 1 ! -regex '^./build\(/.*\)?' ! -regex '^./.git\(/.*\)?' ! -regex '^./node_modules\(/.*\)?' -delete
        sudo mv ./build/* .

    - name: Log filesystem
      run: ls -a
